### ISSUE TITLE
Add search box to each page

### ISSUE THREAD

**Issue by Toddses** [RainyDayMedia/carbide-probes#21] opened 2015-09-17 14:14 UTC
just like on the landing page

**Comment by jonathanhauge** [comment] 2015-09-17 14:15
This is a duplicate of Issue #13

**Comment by jonathanhauge** [comment] 2015-09-17 14:16
Issue #13 was closed. Yet had additional information about Search Results. Does that portion need to be recreated?

**Comment by Toddses** [comment] 2015-09-17 14:17
Already did it. They just needed to be two issues as they aren't really related to each other.

**Closed** 2015-09-28 15:02 UTC
Labels: Dev, enhancement
